# Generated by Django 2.2.4 on 2019-08-24 17:17

import datetime
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StockURL', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockInfoNSE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Date')),
                ('open', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('high', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('low', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('offer', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=20)),
                ('volume', models.IntegerField()),
            ],
        ),
    ]
